name: Java Release

on:
  workflow_call:
    inputs:
      version:
        description: Version to release
        type: string
        required: true
      development_version:
        description: Next version to set in pom.xml after release. Suffix "-SNAPSHOT" is added automatically.
        type: string
        required: true
      java_version:
        description: Java version to use with the setup-java action
        type: string
        required: true
      update_manifests:
        description: Whether to update Kubernetes manifests. Requires setting an IMAGE_NAME variable in your repository.
        type: boolean
        required: false
        default: false

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Set up Java build environment
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: 'maven'

    - name: Set up Git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Update CHANGELOG.md
      id: update_changelog
      uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
      with:
        tag: v${{ inputs.version }}

    - name: Commit CHANGELOG.md
      run: |
        git add CHANGELOG.md
        git commit -m "Add version ${VERSION} to CHANGELOG.md"
      env:
        VERSION: ${{ inputs.version }}

    - name: Prepare Maven release
      run: |
        mvn -B \
          -Darguments=-DskipTests \
          -DautoVersionSubmodules=true \
          -DreleaseVersion="$VERSION" \
          -DscmReleaseCommitComment="Release version $VERSION" \
          -DdevelopmentVersion="${DEV_VERSION}-SNAPSHOT" \
          -DscmDevelopmentCommitComment="Next development version - $DEV_VERSION" \
          -Dtag="v${VERSION}" \
          -Dusername=${{ github.actor }} \
          -Dpassword=${{ secrets.GITHUB_TOKEN }} \
          release:prepare
      env:
        VERSION: ${{ inputs.version }}
        DEV_VERSION: ${{ inputs.development_version }}

    - name: Create GitHub release
      uses: softprops/action-gh-release@v3
      with:
        body: ${{ steps.update_changelog.outputs.release-notes }}
        draft: false
        prerelease: false
        name: ${{ inputs.version }}
        tag_name: v${{ inputs.version }}
        generate_release_notes: false

    - name: Update Kubernetes manifests
      if: ${{ inputs.update_manifests }}
      uses: fjogeleit/yaml-update-action@v0.17.0
      with:
        changes: |
          {
            "k8s/prod/deployment.yaml": {
              "spec.template.spec.containers[0].image": "${{ vars.IMAGE_NAME }}:${{ inputs.version }}"
            },
            "k8s/stage/deployment.yaml": {
              "spec.template.spec.containers[0].image": "${{ vars.IMAGE_NAME }}:${{ inputs.version }}"
            }
          }
        branch: main
        commitChange: true
        message: "Update Kubernetes manifests for release ${{ inputs.version }}"

    - name: Build release artifacts
      run: |
        gh workflow run build.yaml --ref "v${VERSION}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ inputs.version }}

    - name: Build snapshot artifacts
      run: |
        gh workflow run build.yaml --ref main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
